server:
  port: 7070


eureka:
  instance:
    hostname: eureka-provider01
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://root:rootjy@localhost:8761/eureka/, http://root:rootjy@localhost:8762/eureka/

spring:
  application:
    name: eureka-provider

management:
  endpoints:
    web:
      exposure:
        include: shutdown
  endpoint:
    shutdown:
      enabled: true